./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_1_RNA_ONLY_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_1_RNA_ONLY_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 

./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_2_RNA_ONLY_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_2_RNA_ONLY_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 

./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_3_RNA_ONLY_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_3_RNA_ONLY_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 

./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_4_RNA_ONLY_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_4_RNA_ONLY_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 


./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_1_RNA_ALL_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_1_RNA_ALL_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 

./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_2_RNA_ALL_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_2_RNA_ALL_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 

./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_3_RNA_ALL_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_3_RNA_ALL_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 

./table_annovar.pl  /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarInput/ROCR2_A_4_RNA_ALL_annovar.txt humandb/  -buildver hg38 -out /ddn/gs1/home/li11/project2021/SEQC/dataFromFDA/ROCR2_sampleA/AnnoVarAnalysis/annovarOutput/ROCR2_A_4_RNA_ALL_hg38 -remove -protocol refGene,cytoBand,exac03,avsnp147,dbnsfp30a -operation gx,r,f,f,f -nastring . -csvout -polish -xref example/gene_xref.txt 

